date: 2019-08-05 15:15
app: markdown
layout: 'post'
title: 'Lustre故障跟踪之ldlm_resource_complain'
tags: Lustre

## 1 问题描述
今天运维同事反馈过来一个问题，有个集群的客户端重启后无法挂载Lustre，报错信息如下：
```bash
[root@host-xx-xx-xx-xx ~]# mount.lustre -o localflock xx.xx.xx.202@o2ib:xx.xx.xx.201@o2ib:/shlfs /mnt/lustre/
mount.lustre: mount xx.xx.xx.202@o2ib:xx.xx.xx.201@o2ib:/shlfs at /mnt/lustre failed: Input/output error
Is the MGS running?
```
Lustre集群的信息如下：
- Lustre版本
    - 2.8.0
- 是否使用IB
    - Yes

## 2 客户端日志
客户端的dmesg信息如下所示：
```bash
[162983.746777] LustreError: 166-1: MGCxx.xx.xx.202@o2ib: Connection to MGS (at xx.xx.xx.202@o2ib) was lost; in progress operations using this service will fail
[162983.753239] LustreError: 28143:0:(ldlm_request.c:125:ldlm_expired_completion_wait()) ### lock timed out (enqueued at 1564973016, 300s ago), entering recovery for MGS@MGCxx.xx.xx.202@o2ib_0 ns: MGCxx.xx.xx.202@o2ib lock: ffff883e064a4400/0x460c6f21125734b1 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 1 type: PLN flags: 0x1000000000000 nid: local remote: 0xa68b3e19634974ca expref: -99 pid: 28143 timeout: 0 lvb_type: 0
[162983.753621] LustreError: 28218:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.202@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount nonzero (1) after lock cleanup; forcing cleanup.
[162983.753627] LustreError: 28218:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount = 2
[162983.753631] LustreError: 28218:0:(ldlm_resource.c:1523:ldlm_resource_dump()) Waiting locks:
[162983.753640] LustreError: 28218:0:(ldlm_resource.c:1525:ldlm_resource_dump()) ### ### ns: MGCxx.xx.xx.202@o2ib lock: ffff883e064a4400/0x460c6f21125734b1 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 2 type: PLN flags: 0x1106400000000 nid: local remote: 0xa68b3e19634974ca expref: -99 pid: 28143 timeout: 0 lvb_type: 0
[162983.753644] LustreError: 28218:0:(ldlm_resource.c:1525:ldlm_resource_dump()) Skipped 1 previous similar message
[162983.753662] Lustre: MGCxx.xx.xx.202@o2ib: Connection restored to MGCxx.xx.xx.202@o2ib_0 (at xx.xx.xx.202@o2ib)
[163284.097045] LustreError: 15c-8: MGCxx.xx.xx.202@o2ib: The configuration from log 'shlfs-client' failed (-5). This may be the result of communication errors between this node and the MGS, a bad configuration, or other errors. See the syslog for more information.
[163284.106850] Lustre: Unmounted shlfs-client
[163284.107516] LustreError: 28143:0:(obd_mount.c:1426:lustre_fill_super()) Unable to mount  (-5)
```

从客户端的日志中有一条日志特别突出：
```bash
[162983.753621] LustreError: 28218:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.202@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount nonzero (1) after lock cleanup; forcing cleanup.
[162983.753627] LustreError: 28218:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff8817ed040780) refcount = 2
```
为什么这里的引用计数不是0？

## 3 换一个客户端查看系统日志
换一个正常挂载的客户端(之前挂载的)，看下系统日志的信息，是否有LustreError:
```bash
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.201@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff880ff1e7dec0) refcount nonzero (1) after lock cleanup; forcing cleanup
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:887:ldlm_resource_complain()) Skipped 1 previous similar message
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff880ff1e7dec0) refcount = 2
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:1523:ldlm_resource_dump()) Waiting locks:
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:1525:ldlm_resource_dump()) ### ### ns: MGCxx.xx.xx.201@o2ib lock: ffff881186771600/0x447cc722478a6871 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 2 type: PLN flags: 0x1106400000000 nid: local remote: 0xa68b3e19bf922f9c expref: -99 pid: 4762 timeout: 0 lvb_type: 0
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: LustreError: 47937:0:(ldlm_resource.c:1525:ldlm_resource_dump()) Skipped 1 previous similar message
Aug  5 11:28:14 SH-IDC1-10-5-34-21 kernel: Lustre: MGCxx.xx.xx.201@o2ib: Connection restored to xx.xx.xx.202@o2ib (at xx.xx.xx.202@o2ib)
```
从日志可以看出，也是引用计数的问题。

做了一个简单的测试，在这个“正常”的客户端上挂载Lustre到另一个目录，结果是无法挂载。

## 4 看下OSS的系统日志
查看OSS上的系统日志：
```bash
Aug  5 15:49:56 oss03 kernel: LustreError: 166-1: MGCxx.xx.xx.201@o2ib: Connection to MGS (at xx.xx.xx.202@o2ib) was lost; in progress operations using this service will fail
Aug  5 15:49:56 oss03 kernel: LustreError: Skipped 1 previous similar message
Aug  5 15:49:56 oss03 kernel: LustreError: 120217:0:(ldlm_request.c:125:ldlm_expired_completion_wait()) ### lock timed out (enqueued at 1564991096, 300s ago), entering recovery for MGS@MGCxx.xx.xx.201@o2ib_1 ns: MGCxx.xx.xx.201@o2ib lock: ffff883967133e00/0xfa54f25fce2bcb79 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 1 type: PLN flags: 0x1000000000000 nid: local remote: 0xa68b3e1c444ffe00 expref: -99 pid: 120217 timeout: 0 lvb_type: 0
Aug  5 15:49:56 oss03 kernel: LustreError: 120217:0:(ldlm_request.c:125:ldlm_expired_completion_wait()) Skipped 1 previous similar message
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:887:ldlm_resource_complain()) MGCxx.xx.xx.201@o2ib: namespace resource [0x73666c6873:0x0:0x0].0x0 (ffff8846f25d0e40) refcount nonzero (1) after lock cleanup; forcing cleanup.
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:887:ldlm_resource_complain()) Skipped 1 previous similar message
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:1502:ldlm_resource_dump()) --- Resource: [0x73666c6873:0x0:0x0].0x0 (ffff8846f25d0e40) refcount = 2
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:1523:ldlm_resource_dump()) Waiting locks:
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:1525:ldlm_resource_dump()) ### ### ns: MGCxx.xx.xx.201@o2ib lock: ffff883967133e00/0xfa54f25fce2bcb79 lrc: 4/1,0 mode: --/CR res: [0x73666c6873:0x0:0x0].0x0 rrc: 2 type: PLN flags: 0x1106400000000 nid: local remote: 0xa68b3e1c444ffe00 expref: -99 pid: 120217 timeout: 0 lvb_type: 0
Aug  5 15:49:56 oss03 kernel: LustreError: 160833:0:(ldlm_resource.c:1525:ldlm_resource_dump()) Skipped 1 previous similar message
Aug  5 15:49:56 oss03 kernel: Lustre: MGCxx.xx.xx.201@o2ib: Connection restored to MGCxx.xx.xx.201@o2ib_1 (at xx.xx.xx.202@o2ib)
```

## 5 解决方案
明显这里是mgt被锁住了，导致所有客户端和OSS节点无法加锁。有两个解决方案：
1、升级代码到2.9.0
[https://jira.whamcloud.com/browse/LU-7626](https://jira.whamcloud.com/browse/LU-7626)社区有这个问题的反馈，这是一个bug，在2.9.0中被修复，修复的代码详见：[https://review.whamcloud.com/#/c/17791/3/lustre/ldlm/ldlm_lock.c](https://review.whamcloud.com/#/c/17791/3/lustre/ldlm/ldlm_lock.c)，具体原理在jira中已经说明，这里暂时不展开

2、本文的解决方案
be









